"""added image field in campaign model

Revision ID: 558bc4ae3e09
Revises: 822384770b32
Create Date: 2025-10-24 18:20:01.019387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558bc4ae3e09'
down_revision = '822384770b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camp_img', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('camp_img')

    # ### end Alembic commands ###
