"""Change the model

Revision ID: 754d5ba932b1
Revises: e829fd8fbb7f
Create Date: 2025-10-31 16:26:14.800057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754d5ba932b1'
down_revision = 'e829fd8fbb7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('exp_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.alter_column('exp_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
