"""added image field in campaign model

Revision ID: 979027269153
Revises: 558bc4ae3e09
Create Date: 2025-10-24 18:21:14.899406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979027269153'
down_revision = '558bc4ae3e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
