"""Made request_id nullable

Revision ID: 0433da6bc0d1
Revises: 663f50edb5cf
Create Date: 2025-10-13 17:57:36.239295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0433da6bc0d1'
down_revision = '663f50edb5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_history', schema=None) as batch_op:
        batch_op.alter_column('request_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_history', schema=None) as batch_op:
        batch_op.alter_column('request_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
